[package]
name = "schematics"
version = "0.1.0"
edition = "2021"

[dependencies]
valence = { workspace = true }
valence_nbt = { workspace = true, features = ["serde"]  }
thiserror = { workspace = true }