[package]
name = "combat"
version = "0.1.0"
edition = "2021"

[dependencies]
valence = { workspace = true }
utils = { workspace = true }
fall_damage = { workspace = true }
tracing = { workspace = true }
rand = { workspace = true }
